name: Merge and Deploy

on:
  workflow_dispatch:

jobs:
  merge_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Merge main into develop and bump version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout develop
        git pull origin develop

        # Merge main into develop
        git merge origin/main

        # Bump the version
        poetry version patch
        NEW_VERSION=$(poetry version -s)

        # Commit the version bump
        git add pyproject.toml poetry.lock
        git commit -m "Bump version to $NEW_VERSION"

        # Push changes to develop
        git push origin develop

    - name: Merge pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pr_number=$(gh pr list --state open --base main --head develop --json number --jq '.[0].number')
        gh pr merge $pr_number --squash --admin --repo ${{ github.repository }}

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish --build --username __token__ --password $PYPI_TOKEN
