name: Restrict Merging to Main

on:
  pull_request:
    branches:
      - acceptance

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Check source branch
      run: |
        if [[ ${{ github.head_ref }} != "develop" ]]; then
          echo "Pull requests to main must come from the develop branch."
          exit 1
        fi
